spring:
  application:
    name: eureka-remote-server

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false  #Para que no se registre así mismo como cliente
    fetchRegistry: false       #Para que no se registre así mismo como cliente
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0